# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 5df1a4bf6f04a1ed3a643167b38d502575e29aef
    hooks:
    -   id: trailing-whitespace
        exclude: ^docs/|tests/$
    -   id: end-of-file-fixer
        exclude: ^docs/|tests/$
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: masterpylintrc
        name: Overwrite local .pylintrc by master one
        entry: cp ../.pylintrc ./.pylintrc
        pass_filenames: false
        always_run: true
        language: system
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
    -   id: pylint
        files: ^pyppl_report/.+$
        pass_filenames: false
        types: [python]
        args: [pyppl_report]
-   repo: local
    hooks:
    -   id: poetry2setuppy
        name: Convert pyproject.toml to setup.py
        entry: dephell deps convert --from=poetry --to=setup.py
        language: system
        files: pyproject.toml
        pass_filenames: false
    -   id: poetry2requirements
        name: Convert pyproject.toml to requirements.txt
        entry: dephell deps convert --from=poetry --to=requirements.txt
        language: system
        files: pyproject.toml
        pass_filenames: false
    -   id: gendocbootstrip
        name: "Generate bootstrip docs"
        entry: >
          pyppl report -i tests/data/test.md
                          -o docs/bootstrap.html
                          -n false
                          --title "Bootstrap template for pyppl_report"
                          --template bootstrap
        language: system
        files: ^tests/data/|^pyppl_report/
        pass_filenames: false
    -   id: gendoclayui
        name: "Generate layui docs"
        entry: >
          pyppl report -i tests/data/test.md
                          -o docs/layui.html
                          -n false
                          --title "Layui template for pyppl_report"
                          --template layui
        language: system
        files: ^tests/data/|^pyppl_report/
        pass_filenames: false
    -   id: gendocsemantic
        name: "Generate semantic docs"
        entry: >
          pyppl report -i tests/data/test.md
                          -o docs/semantic.html
                          -n false
                          --title "Senmantic template for pyppl_report"
                          --template semantic
        language: system
        files: ^tests/data/|^pyppl_report/
        pass_filenames: false
    -   id: pytest
        name: Run pytest
        entry: pytest
        language: system
        args: [tests/]
        pass_filenames: false
        files: ^tests/.+$|^pyppl_report/.+$
