language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
before_install:
  - pip install poetry
  - curl -L https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb > pandoc.deb # apt doesn't install latest pandoc
  - sudo dpkg -i pandoc.deb
  - sudo apt-get update
  - sudo apt-get install xvfb libfontconfig xfonts-75dpi xfonts-base
  - curl -L https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb > wkhtmltox.deb
  - sudo dpkg -i wkhtmltox.deb
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - poetry install -v
  - ./cc-test-reporter before-build
script:
  - pytest tests/ -s
after_success: |
  if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then
    ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  fi
deploy:
  provider: script
  script: poetry publish --build -u $PYPI_USER -p $PYPI_PASSWORD
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
