language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
before_install:
  - pip install poetry
  - curl -L https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb > pandoc.deb # apt doesn't install latest pandoc
  - sudo dpkg -i pandoc.deb
  - curl -L https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb > wkhtmltox.deb
  - sudo dpkg -i wkhtmltox.deb
install:
  - poetry install -v
  - pip install tox-travis
  - pip install codacy-coverage
script:
  - pytest tests/ -s
after_success: |
  if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then
    python-codacy-coverage -r .coverage.xml
  fi
deploy:
  provider: script
  script: poetry publish --build -u $PYPI_USER -p $PYPI_PASSWORD
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
