site_name: pyppl-report
theme:
    name: 'material'
    font:
      text: 'Ubuntu'
      code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
nav:
    - 'Introduction': 'index.md'
    - 'How it works': 'howItWorks.md'
    - 'Using process envs': 'processEnvs.md'
    - 'HTML components': 'HTMLComponents.md'
    - 'Change log': 'CHANGELOG.md'